# Generated by Django 3.2.5 on 2024-08-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tokenscustom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenscustom',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
