# Generated by Django 3.2.5 on 2024-08-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_totpdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TOTPDevice',
        ),
    ]
