# Generated by Django 3.2.5 on 2024-08-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_totpdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twoFA',
            field=models.BooleanField(default=False),
        ),
    ]
