version: '3'
services:

  pong:
    build: ./pong
    image: pong
    container_name: pong
    restart: always
    depends_on:
      - database
    volumes:
      - PongVol:/usr/src/app
      - StaticVol:/usr/src/app/staticfiles/
    ports:
      - 8443:8443
    networks:
      - net

  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - DatabaseVol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: db_pong
    networks:
      - net

  frontend:
      image: nginx:1.27.0
      container_name: frontend
      restart: always
      volumes:
        - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./frontend/ssl:/etc/nginx/ssl:ro
        - FrontVol:/usr/share/nginx/html
        - StaticVol:/staticfiles/
      ports:
        - 443:443
      networks:
        - net

  # rachid part
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8008:8080
    networks:
      - net
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - net


volumes:
  StaticVol:
    driver: local
    driver_opts:
      type: none
      device: /Users/${USER}/Desktop/back-end/pong/volumes/StaticVol
      o: bind
  PongVol:
    driver: local
    driver_opts:
      type: none
      device: /Users/${USER}/Desktop/back-end/pong/volumes/PongVol
      o: bind
  DatabaseVol:
    driver: local
    driver_opts:
      type: none
      device: /Users/${USER}/Desktop/back-end/pong/volumes/DatabaseVol
      o: bind
  FrontVol:
    driver: local
    driver_opts: 
      type: none
      device: /Users/${USER}/Desktop/back-end/frontend/FrontVol
      o: bind


networks:
  net:
