# Generated by Django 3.2.5 on 2024-08-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_last_seen'),
        ('users', '0008_tokenscustom_retired'),
    ]

    operations = [
    ]
