# Generated by Django 3.2.5 on 2024-08-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_twofa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenscustom',
            name='retired',
        ),
    ]
