# Generated by Django 3.2.5 on 2024-09-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_verification_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='verification_code',
        ),
    ]
