# Generated by Django 3.2.5 on 2024-10-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20241002_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_wins',
            field=models.IntegerField(default=0),
        ),
    ]
