# Generated by Django 3.2.5 on 2024-10-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_user_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_name', max_length=25, unique=True),
        ),
    ]
